fix:  Error: Cannot find module 'eslint/lib/formatters/stylish' (#66)
* * .gitignore: add /src-cordova/node_modules that is generated by Cordova 8+ (#46)

* ESLint ignore paths beginning with . (#47)

* fix: Temporary until ajv-errors package gets a proper fix

* Revert "fix: Temporary until ajv-errors package gets a proper fix"

This reverts commit 955c710778de19f75b6bb8d910fdad93d5b8e6fe.

* chore: Update README

* fix:  Error: Cannot find module 'eslint/lib/formatters/stylish'

If anyone upgrades to eslint ^6.0.0 the quasar build breaks with `Module build failed: Error: Cannot find module 'eslint/lib/formatters/stylish'`
It's because they changed the following path:
```
eslint 5.x: eslint/lib/formatters/stylish
eslint 6.x: eslint/lib/cli-engine/formatters/stylish
```
This works for loaders that use the `CLIEngine.getFormatter` API, but eslint-loader did not.
Fortunately, you can manually fix this by making the loader look like this:
```js
      extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          options: {
            cache: true,
            failOnError: true,
            formatter: require('eslint').CLIEngine.getFormatter('stylish')
          }
        })
      }
```
Notice the options. I have run and verified this. Also works for version < 6

* Update quasar.conf.js